evolution ssl cassandra39 v1.8

diff --git a/jobs/cassandra_seed/templates/ssl3/ssl_env.ctl.erb b/jobs/cassandra_seed/templates/ssl3/ssl_env.ctl.erb
--- a/jobs/cassandra_seed/templates/ssl3/ssl_env.ctl.erb
+++ b/jobs/cassandra_seed/templates/ssl3/ssl_env.ctl.erb
@@ -1,6 +1,6 @@
 #!/bin/bash
 #set -x
-set -e # exit immediately if a simple command exits with a non-zero status.
+#set -e # exit immediately if a simple command exits with a non-zero status.
 set -u # report the usage of uninitialized variables.
 
 export JAVA_HOME=/var/vcap/packages/openjdk
